#-------------------------------
# General Site Settings

title: Serac Studio
logo: "assets/images/icons/serac_studio_logo_2.png"
author: seracstudio
description: Serac Studio is an indie video games' developer
email: seracstudio@gmail.com
address: Mostoles, Comunidad de Madrid, Spain
copyright: Copyright &copy; 2020 Designed by Serac Studio

menu:
- {name: Our project, link: '/portfolio/#crystalwars'}
#- {name: Portfolio, link: '/portfolio/#portafolio'}
#- {name: Team, link: '/portfolio/#team'}
- {name: Know us, link: '/portfolio/#blog'}
- {name: Merchan, link: '/portfolio/#merchan'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! We are <br> Serac Studio

social:
- {icon: "assets/images/icons/twitter_5.png", link: "https://twitter.com/StudioSerac"}
- {icon: "assets/images/icons/itchio_1.png", link: "https://seracstudio.itch.io/guildmasters-heredity"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Serac Studio is a small studio who makes very cool games


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - image : "assets/images/icons/card_1.png"
    content: "Nuestro proyecto actual se llama Crystal Wars, un juego de cartas sobre una guerra entre dioses y no nos decidimos en poner nombre a las cartas"

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/merchan.png"
    url: "/portfolio/2020/11/14/merchandising/"
    
#-------------------------------
# Services Section
services-title: GuildMasters' Heritage
services:
- {
    name: ,
    icon: "assets/images/icons/every_protagonist_trans.png",
    description: 'These are Arcelia and her miner robot S.O.R.A., you must help them to collect as many treasures as you can before something appears in the mine....',
    active: # Add true to select section
  }
- {
    name: ,
    icon: ,
    description: 'Your friend and you will become the members of GuildMasters, an explorer guild',
    active:  # Add true to select section
  }
- {
    name: ,
    icon: "assets/images/icons/every_enemy_trans.png",
    description: 'Plenty of enemies lives in the mine. Be careful, ranger! One bad step and your life will end',
    active: # Add true to select section
  }



# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:

    
  - image : "assets/images/portfolio/script.jpg"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Pablo"
    image: "assets/images/team/pablo_1.png"
    designation : "Narrative Designer"
    content : ""
    
  - name: "Alejandro"
    image: "assets/images/team/alejandro_1.png"
    designation: "Art Director"
    content: 
    
  - name: "Germán"
    image: "assets/images/team/german_1.png"
    designation: "Programmer"
    content: 

  - name: "Dilan"
    image: "assets/images/team/dilan_1.png"
    designation: "Game Designer"
    content: 
    
  - name: "Darío"
    image: "assets/images/team/dario_1.png"
    designation: "Programmer"
    content: 
    
  - name: "Enrique"
    image: "assets/images/team/enrique_1.png"
    designation: "Programmer"
    content: 
    
#-------------------------------
# Client Slider Section

#-------------------------------
# Contact Section

